"""create MVP schema

Revision ID: 2874806da0ef
Revises:
Create Date: 2026-09-04 17:11:43.512095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2874806da0ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


RLS_OWNERSHIP_EXPRESSIONS = {
    "users": "id = (select auth.uid())",
    "websites": "user_id = (select auth.uid())",
    "analysis_runs": "EXISTS (SELECT 1 FROM websites w WHERE w.id = website_id AND w.user_id = (select auth.uid()))",
    "keywords": "EXISTS (SELECT 1 FROM analysis_runs ar JOIN websites w ON w.id = ar.website_id WHERE ar.id = analysis_run_id AND w.user_id = (select auth.uid()))",
    "suggestions": "EXISTS (SELECT 1 FROM analysis_runs ar JOIN websites w ON w.id = ar.website_id WHERE ar.id = analysis_run_id AND w.user_id = (select auth.uid()))",
    "technical_findings": "EXISTS (SELECT 1 FROM analysis_runs ar JOIN websites w ON w.id = ar.website_id WHERE ar.id = analysis_run_id AND w.user_id = (select auth.uid()))",
    "reports": "EXISTS (SELECT 1 FROM websites w WHERE w.id = website_id AND w.user_id = (select auth.uid()))",
    "organizer_items": "EXISTS (SELECT 1 FROM websites w WHERE w.id = website_id AND w.user_id = (select auth.uid()))",
    "suggestion_keywords": "EXISTS (SELECT 1 FROM suggestions s JOIN analysis_runs ar ON ar.id = s.analysis_run_id JOIN websites w ON w.id = ar.website_id WHERE s.id = suggestion_id AND w.user_id = (select auth.uid()))",
    "suggestion_technical_findings": "EXISTS (SELECT 1 FROM suggestions s JOIN analysis_runs ar ON ar.id = s.analysis_run_id JOIN websites w ON w.id = ar.website_id WHERE s.id = suggestion_id AND w.user_id = (select auth.uid()))",
    "organizer_stage_history": "EXISTS (SELECT 1 FROM organizer_items oi JOIN websites w ON w.id = oi.website_id WHERE oi.id = organizer_item_id AND w.user_id = (select auth.uid()))",
}


def enable_supabase_rls() -> None:
    """Create Supabase ownership policies only when migrating PostgreSQL."""

    if op.get_bind().dialect.name != "postgresql":
        return

    for table_name, ownership_expression in RLS_OWNERSHIP_EXPRESSIONS.items():
        op.execute(f'ALTER TABLE "{table_name}" ENABLE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY "{table_name}_owner_access" ON "{table_name}" '
            f"FOR ALL TO authenticated USING ({ownership_expression}) "
            f"WITH CHECK ({ownership_expression})"
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_context', sa.Text(), nullable=True),
    sa.Column('google_ads_connected', sa.Boolean(), nullable=False),
    sa.Column('ga4_connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_websites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_websites')),
    sa.UniqueConstraint('user_id', 'url', name=op.f('uq_websites_user_id'))
    )
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_websites_user_id'), ['user_id'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'scraping', 'analyzing', 'generating', 'completed', 'failed', name='analysis_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('pages_scanned_count', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('health_score IS NULL OR (health_score >= 0 AND health_score <= 100)', name=op.f('ck_analysis_runs_health_score_range')),
    sa.CheckConstraint('pages_scanned_count >= 0', name=op.f('ck_analysis_runs_pages_scanned_nonnegative')),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_analysis_runs_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_website_id'), ['website_id'], unique=False)

    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=500), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('tfidf_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('search_intent', sa.Enum('informational', 'navigational', 'commercial', 'transactional', name='search_intent', native_enum=False, create_constraint=True), nullable=True),
    sa.CheckConstraint('frequency >= 0', name=op.f('ck_keywords_frequency_nonnegative')),
    sa.CheckConstraint('tfidf_score >= 0', name=op.f('ck_keywords_tfidf_score_nonnegative')),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_keywords_analysis_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords')),
    sa.UniqueConstraint('analysis_run_id', 'phrase', name=op.f('uq_keywords_analysis_run_id'))
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keywords_analysis_run_id'), ['analysis_run_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('health_score_delta', sa.Integer(), nullable=True),
    sa.Column('aeo_completion_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('aeo_completion_delta', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('technical_findings_resolved', sa.Integer(), nullable=False),
    sa.Column('technical_findings_open', sa.Integer(), nullable=False),
    sa.Column('content_published_count', sa.Integer(), nullable=False),
    sa.Column('top_keywords', sa.JSON(), nullable=False),
    sa.Column('sem_accepted_count', sa.Integer(), nullable=False),
    sa.Column('sem_cost_tier_breakdown', sa.JSON(), nullable=False),
    sa.Column('ad_groups_defined_count', sa.Integer(), nullable=False),
    sa.Column('organizer_stage_counts', sa.JSON(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('ga4_sessions', sa.Integer(), nullable=True),
    sa.Column('ga4_new_users', sa.Integer(), nullable=True),
    sa.Column('ga4_returning_users', sa.Integer(), nullable=True),
    sa.Column('ga4_conversions', sa.Integer(), nullable=True),
    sa.Column('ga4_revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('real_ad_spend', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('real_roi_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('aeo_completion_pct >= 0 AND aeo_completion_pct <= 100', name=op.f('ck_reports_aeo_completion_range')),
    sa.CheckConstraint('health_score >= 0 AND health_score <= 100', name=op.f('ck_reports_health_score_range')),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_reports_analysis_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_reports_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('analysis_run_id', name=op.f('uq_reports_analysis_run_id'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_website_id'), ['website_id'], unique=False)

    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('affected_page_url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.Enum('aeo', 'seo_content', 'sem', name='suggestion_category', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('starter_outline', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='suggestion_priority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('acceptance_status', sa.Enum('pending', 'accepted', 'dismissed', name='acceptance_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('dismiss_reason', sa.Enum('not_relevant', 'too_much_work', 'already_doing_this', 'other', name='dismiss_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('cost_tier', sa.Enum('low', 'medium', 'high', name='cost_tier', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('cpc_low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cpc_high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('ad_group_label', sa.String(length=300), nullable=True),
    sa.Column('ad_copy_angle', sa.Text(), nullable=True),
    sa.Column('landing_page_match', sa.Text(), nullable=True),
    sa.Column('targeting_notes', sa.Text(), nullable=True),
    sa.Column('negative_keywords', sa.JSON(), nullable=True),
    sa.Column('cheaper_alternative_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(acceptance_status = 'dismissed' AND dismiss_reason IS NOT NULL) OR (acceptance_status != 'dismissed' AND dismiss_reason IS NULL)", name=op.f('ck_suggestions_dismiss_reason_matches_status')),
    sa.CheckConstraint("category = 'sem' OR (cost_tier IS NULL AND cpc_low IS NULL AND cpc_high IS NULL AND search_volume IS NULL AND ad_group_label IS NULL AND ad_copy_angle IS NULL AND landing_page_match IS NULL AND targeting_notes IS NULL AND negative_keywords IS NULL)", name=op.f('ck_suggestions_sem_fields_only_for_sem')),
    sa.CheckConstraint('cpc_low IS NULL OR cpc_high IS NULL OR cpc_low <= cpc_high', name=op.f('ck_suggestions_cpc_range_order')),
    sa.CheckConstraint('search_volume IS NULL OR search_volume >= 0', name=op.f('ck_suggestions_search_volume_nonnegative')),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_suggestions_analysis_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cheaper_alternative_to_id'], ['suggestions.id'], name=op.f('fk_suggestions_cheaper_alternative_to_id_suggestions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestions'))
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestions_analysis_run_id'), ['analysis_run_id'], unique=False)

    op.create_table('technical_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('affected_page_url', sa.String(length=2048), nullable=True),
    sa.Column('related_page_url', sa.String(length=2048), nullable=True),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='finding_severity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('resolution_status', sa.Enum('open', 'resolved', name='resolution_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_technical_findings_analysis_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_findings'))
    )
    with op.batch_alter_table('technical_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technical_findings_analysis_run_id'), ['analysis_run_id'], unique=False)

    op.create_table('organizer_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.Enum('aeo', 'seo_content', 'sem', name='organizer_item_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('stage', sa.Enum('backlog', 'in_production', 'in_review', 'published', name='organizer_stage', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], name=op.f('fk_organizer_items_suggestion_id_suggestions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_organizer_items_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizer_items')),
    sa.UniqueConstraint('suggestion_id', name=op.f('uq_organizer_items_suggestion_id'))
    )
    with op.batch_alter_table('organizer_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizer_items_website_id'), ['website_id'], unique=False)

    op.create_table('suggestion_keywords',
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('recommended_usage_count', sa.Integer(), nullable=True),
    sa.CheckConstraint('recommended_usage_count IS NULL OR recommended_usage_count >= 0', name=op.f('ck_suggestion_keywords_recommended_usage_nonnegative')),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_suggestion_keywords_keyword_id_keywords'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], name=op.f('fk_suggestion_keywords_suggestion_id_suggestions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('suggestion_id', 'keyword_id', name=op.f('pk_suggestion_keywords'))
    )
    op.create_table('suggestion_technical_findings',
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('technical_finding_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], name=op.f('fk_suggestion_technical_findings_suggestion_id_suggestions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technical_finding_id'], ['technical_findings.id'], name=op.f('fk_suggestion_technical_findings_technical_finding_id_technical_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('suggestion_id', 'technical_finding_id', name=op.f('pk_suggestion_technical_findings'))
    )
    op.create_table('organizer_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizer_item_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.Enum('backlog', 'in_production', 'in_review', 'published', name='organizer_stage_from', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('to_stage', sa.Enum('backlog', 'in_production', 'in_review', 'published', name='organizer_stage_to', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizer_item_id'], ['organizer_items.id'], name=op.f('fk_organizer_stage_history_organizer_item_id_organizer_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizer_stage_history'))
    )
    with op.batch_alter_table('organizer_stage_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizer_stage_history_organizer_item_id'), ['organizer_item_id'], unique=False)

    enable_supabase_rls()

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizer_stage_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizer_stage_history_organizer_item_id'))

    op.drop_table('organizer_stage_history')
    op.drop_table('suggestion_technical_findings')
    op.drop_table('suggestion_keywords')
    with op.batch_alter_table('organizer_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizer_items_website_id'))

    op.drop_table('organizer_items')
    with op.batch_alter_table('technical_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technical_findings_analysis_run_id'))

    op.drop_table('technical_findings')
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_analysis_run_id'))

    op.drop_table('suggestions')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_website_id'))

    op.drop_table('reports')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_analysis_run_id'))

    op.drop_table('keywords')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_website_id'))

    op.drop_table('analysis_runs')
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_websites_user_id'))

    op.drop_table('websites')
    op.drop_table('users')
    # ### end Alembic commands ###
